import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class PrivacyPolicy extends StatelessWidget {
  const PrivacyPolicy({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(backgroundColor: Colors.orange.shade300,),
      body: Container(
        margin: const EdgeInsets.only(top: 10,right: 20,left: 20,bottom: 30),
        child:ListView(
      children: const [
        Text('    Privacy Policy Sanzhar & Parasat & Daryn & Serik & Marlen built the 21 Days Challenge app as an '
            'Ad Supported app. This SERVICE is provided by Kati & Lima at no cost and is '
            'intended for use as is. This page is used to inform visitors regarding my policies'
            ' with the collection, use, and disclosure of Personal Information if anyone decided'
            ' to use my Service. If you choose to use my Service, then you agree to the collection'
            ' and use of information in relation to this policy. The Personal Information that I '
            'collect is used for providing and improving the Service. I will not use or share your '
            'information with anyone except as described in this vacy Policy. The terms used in this'
            ' Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible'
            ' at 21 Days Challenge unless otherwise defined in this Privacy Policy. Information Collection '
            'and Use For a better experience, while using our Service, I may require you to provide us with '
            'certain personally identifiable information, including but not limited to Crashes, Counters. The'
            ' information that I request will be retained on your device and is not collected by me in any way. '
            'The app does use third party services that may collect information used to identify you. Link to '
            'privacy policy of third party service providers used by the app Google Play Services 67 Admob Google'
            ' Analytics for Firebase 67 Firebase Crashlytics 67 Facebook 17 A III.'
            'Log Data'
            'I want to inform you that whenever you use my Service, in'
            'a case of an error in the app I collect data and information'
            '(through third party products) on your phone called Log'
            'Data. This Log Data may include information such as your'
            'device Internet Protocol ("IP") address, device name,'
            'operating system version, the configuration of the app'
            'when utilizing my Service, the time and date of your use'
            'of the Service, and other statistics.'
            '\n\nCookies'
            '\nCookies are files with a small amount of data that are'
            'commonly used as anonymous unique identifiers. These'
            'are sent to your browser from the websites that you visit'
            'and are stored on your devices internal memory. This'
            'Service does not use these "cookies” explicitly. However,'
            'the app may use third party code and libraries that use'
            '"cookies” to collect information and improve their'
            'services. You have the option to either accept or refuse'
            'these cookies and know when a cookie is being sent to'
            'your device. If you choose to refuse our cookies, you may'
            'not be able to use some portions of this Service. Service'
            'Providers I may employ third-party companies and'
            'individuals due to the following reasons:'
            'To facilitate our Service;'
            'To provide the Service on our behalf;'
            'To perform Service-related services; or'
            'To assist us in analyzing how our Service is used.'
            'I want to inform users of this Service that these third'
            'parties have access to your Personal Information. The'
            'reason is to perform the tasks assigned to them on our'
            'behalf. However, they are obligated not to disclose or use'
            'the information for any other purpose.'
            '\n\nSecurity'
            '\nI value your trust in providing us your Personal'
            'Information, thus we are striving to use commercially'
            'acceptable means of protecting it. But remember that no'
            'method of transmission over the internet, or method of'
            'electronic storage is 100% secure and reliable, and I'
            'cannot guarantee its absolute cecurity\n'
            'Security'
            'I value your trust in providing us your Personal'
            'Information, thus we are striving to use commercially'
            'acceptable means of protecting it. But remember that no'
            'method of transmission over the internet, or method of'
            'electronic storage is 100% secure and reliable, and I'
            'cannot guarantee its absolute security.'
            'Links to Other Sites'
            'This Service may contain links to other sites. If you click'
            'on a third-party link, you will be directed to that site. Note'
            'that these external sites are not operated by me.'
            'Therefore, I strongly advise you to review the Privacy'
            '1'
            'Policy of these websites. I have no control over and'
            'assume no responsibility for the content, privacy policies,'
            'or practices of any third-party sites or services.'
            '\n\nChildrens Privacy'
            '\nThese Services do not address anyone under the age of'
            '13. I do not knowingly collect personally identifiable'
            'information from children under 13. In the case I discover'
            'that a child under 13 has provided me with personal'
            'information, I immediately delete this from our servers. If'
            'you are a parent or guardian and you are aware that your'
            'child has provided us with personal information, please'
            'contact me so that I will be able to do necessary actions.'
            'Changes to This Privacy Policy'
            'I may update our Privacy Policy from time to time. Thus,'
            'you are advised to review this page periodically for any'
            'changes. I will notify you of any changes by posting the'
            'new Privacy Policy on this page. This policy is effective as'
            'of 2021-01-01'
            '\n\nContact Us'
            '\nIf you have any questions or suggestions about my'
            'Privacy Policy, do not hesitate to contact me at'
            'support@21dayschallenge.atlassian.net. This privacy'
            'policy page was created at privacypolicytemplate.net and'
            'modified/generated by App Privacy Policy Generator'
            'Terms & Conditions'
            'By downloading or using the app, these terms will'
            'automatically apply to you - you should make sure'
            'therefore that you read them carefully before using the'
            'app. You are not allowed to copy, or modify the app, any'
            'part of the app, or our trademarks in any way. You are not'
            'allowed to attempt to extract the source code of the app,'
            'and you also shouldnt try to translate the app into other'
            'languages, or make derivative versions. The app itself,'
            'and all the trade marks, copyright, database rights and'
            'other intellectual property rights related to it, still belong'
            'to Parasat & Sanzhar & Daryn & Serik & Marlen.'
            'Kati & Lima is committed to ensuring that the app is as'
            'useful and efficient as possible. For that reason, we'
            'reserve the right to make changes to the app or to charge'
            'for its services, at any time and for any reason. We will'
            'never charge you for the app or its services without'
            'making it very clear to you exactly what you are paying for.'
            'The 21 Days Challenge app stores and processes'
            'personal data that you have provided to us, in order to'
            'provide my Service. Its your responsibility to keep your'
            'phone and access to the app secure. We therefore'
            'recommend that you do not jailbreak or root your phone,'
            'which is the process of removing software restrictions'
            'and limitations imposed by the official operating system'
            'of your device. It could make your phone vulnerable to'
            'malware/viruses/malicious programs, compromise your'
            'phones security features and it could mean that the 21'
            'Days Challenge app wont work properly or at all.'
            'The app does use third party services that declare their'
            'own Terms and Conditions.'
            'Link to Terms and Conditions of third party service'
            'providers used by the app'
            '\nGoogle Play Services'
            '\nAdmob'
            '\n67'
            '\nGoogle Analytics for Firebase'


            , style: TextStyle(color: Colors.black,
                fontSize: 20.0,
                fontFamily: 'Indies')),



    ],
        )
    ),
    );
  }


}